excluded: # paths to ignore during linting.
  - Devops
  - Public
  - .build
identifier_name:
  min_length: 2
  max_length: 50

force_try:
  severity: warning 

line_length: 150

trailing_whitespace: 
  ignores_empty_lines: true 

colon:
  apply_to_dictionaries: false

disabled_rules:
  - nesting
  - unused_optional_binding

opt_in_rules:  
  - literal_expression_end_indentation
